name: EAS Build
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and Submit
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Force npm usage
        run: |
          echo "Removing yarn.lock if it exists..."
          rm -f yarn.lock
          echo "Setting npm as package manager..."
          echo "packageManager=npm" >> .npmrc

      - name: Install dependencies with npm
        run: |
          echo "Using npm to install dependencies..."
          npm cache clean --force
          rm -rf node_modules
          npm install --legacy-peer-deps

      - name: Setup CLI tools
        run: |
          echo "Setting up CLI tools..."
          echo "Installing global CLI tools..."
          npm install -g @expo/cli@latest eas-cli@latest

          echo "Creating expo command alias..."
          ln -sf $(which npx) /usr/local/bin/expo || true
          echo '#!/bin/bash' > /tmp/expo
          echo 'npx @expo/cli "$@"' >> /tmp/expo
          chmod +x /tmp/expo
          sudo mv /tmp/expo /usr/local/bin/expo || cp /tmp/expo /usr/local/bin/expo

          echo "Verifying CLI tools..."
          which expo || echo "expo not in PATH"
          expo --version || npx @expo/cli --version
          which eas || echo "eas not in PATH"
          eas --version || npx eas --version

      - name: Authenticate with Expo
        run: |
          echo "Setting up Expo authentication..."
          echo "EXPO_TOKEN is set: $([[ -n "$EXPO_TOKEN" ]] && echo "Yes" || echo "No")"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android APK
        env:
          npm_config_package_manager: npm
          PACKAGE_MANAGER: npm
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          echo "Building with EAS..."
          echo "Current directory: $(pwd)"
          echo "Available commands:"
          which expo eas || echo "Commands not in PATH, using npx"

          echo "Starting EAS build..."
          eas build --platform android --profile preview --non-interactive