name: EAS Build
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and Submit
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Force npm usage
        run: |
          echo "Removing yarn.lock if it exists..."
          rm -f yarn.lock
          echo "Setting npm as package manager..."
          echo "packageManager=npm" >> .npmrc

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies with npm
        run: |
          echo "Using npm to install dependencies..."
          npm cache clean --force
          rm -rf node_modules
          npm install --legacy-peer-deps

      - name: Build Android APK
        env:
          npm_config_package_manager: npm
          PACKAGE_MANAGER: npm
        run: |
          echo "Building with EAS using npm..."
          eas build --platform android --profile preview --non-interactive